//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap24Team3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChinhSuaThongTin
    {
        public int ID { get; set; }
        public int ID_SinhVien { get; set; }
        public string MailCaNhan { get; set; }
        public string DTDD { get; set; }
        public string DTCha { get; set; }
        public string DTMe { get; set; }
        public string DiaChi { get; set; }
        public int ID_DotChinhSua { get; set; }
    
        public virtual DotChinhSuaThongTin DotChinhSuaThongTin { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
