//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap24Team3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhanDaoTao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocPhanDaoTao()
        {
            this.HocPhanDaoTao1 = new HashSet<HocPhanDaoTao>();
            this.RangBuocHocPhans = new HashSet<RangBuocHocPhan>();
            this.RangBuocHocPhans1 = new HashSet<RangBuocHocPhan>();
        }
    
        public int ID { get; set; }
        public string MaHocPhan { get; set; }
        public string TenHocPhan { get; set; }
        public string SoTinChi { get; set; }
        public Nullable<int> HocKy { get; set; }
        public int ID_KhoiKienThuc { get; set; }
        public Nullable<int> ID_HocPhanTuChon { get; set; }
    
        public virtual KhoiKienThuc KhoiKienThuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocPhanDaoTao> HocPhanDaoTao1 { get; set; }
        public virtual HocPhanDaoTao HocPhanDaoTao2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RangBuocHocPhan> RangBuocHocPhans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RangBuocHocPhan> RangBuocHocPhans1 { get; set; }
    }
}
