//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap24Team3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoiKienThuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoiKienThuc()
        {
            this.HocPhanDaoTaos = new HashSet<HocPhanDaoTao>();
        }
    
        public int ID { get; set; }
        public string MaKhoiKienThuc { get; set; }
        public string TenKhoiKienThuc { get; set; }
        public Nullable<int> ID_ChuongTrinhDaoTao { get; set; }
    
        public virtual ChuongTrinhDaoTao ChuongTrinhDaoTao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocPhanDaoTao> HocPhanDaoTaos { get; set; }
    }
}
