//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap24Team3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RangBuocHocPhan
    {
        public int ID { get; set; }
        public Nullable<int> ID_HocPhan { get; set; }
        public Nullable<int> ID_HocPhanRangBuoc { get; set; }
        public string LoaiRangBuoc { get; set; }
    
        public virtual HocPhanDaoTao HocPhanDaoTao { get; set; }
        public virtual HocPhanDaoTao HocPhanDaoTao1 { get; set; }
    }
}
